config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :bugs do
      get 'assign', on: :member
    end
  end

  resources :bugs, only: [] do
    get 'user_bugs', on: :collection
  end

  resources :project_assignments, only: %i[new create destroy]

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify

  has_many :project_assignments, dependent: :destroy
  has_many :projects, through: :project_assignments
  has_many :bugs, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, :email, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, format: Devise.email_regexp
  validates :password, confirmation: true

  validate :user_must_select_atleast_one_role

  def user_must_select_atleast_one_role
    errors.add(:role, ':Atleast one must be checked') if role_ids.empty?
  end

  scope :unassigned_users, ->(project_id) { where.not(id: Project.find(project_id).users).distinct }
end

app/views/users/_users_table.html.erb
<% if users.empty? %>
  <h3 class="table-heading">No <%= user_type + 's' %> found!</h3>
<% else %>
  <table class="table table-hover table-responsive">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Add User</th>
      </tr>
    </thead>

    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Add User', project_assignments_path(project_id: project_id, user_id: user.id, user_type: user_type), method: :post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/index.js.erb
$("#users-table").html("<%= escape_javascript(render partial: 'users_table', locals: { users: @users, project_id: @project_id, user_type: @user_type }) %>");

app/views/users/my_bugs.html.erb
<% if @bugs.count.positive? %>
  <div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 border border-radius-5 p-3 mt-5">
    <h3 class="table-heading">Your Bugs</h3>

    <table class="table table-hover table-responsive">
      <thead class="thead-light">
        <tr>
          <th>Title</th>
          <th>Deadline</th>
          <th>Type</th>
          <th>Status</th>
          <th>Project</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>

      <tbody>
        <% @bugs.includes(:project).each do |bug| %>
          <tr>
            <td><%= link_to bug.title, project_bug_path(bug.project, bug) %></td>
            <td><%= bug.deadline %></td>
            <td><%= bug.bug_type.capitalize %></td>
            <td><%= bug.status.capitalize %></td>
            <td><%= link_to bug.project.name, project_path(bug.project) %></td>
            <td><%= link_to 'Edit', edit_project_bug_path(bug.project, bug) %></td>
            <td><%= link_to 'Destroy', project_bug_path(bug.project, bug), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class=" counter col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3 border border-radius-5 p-3 mt-3">
    <h3 class="count-heading mt-3 mx-4">You don't have any bugs yet!</h3>
  </div>
<% end %>