config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :bugs do
      get 'assign', on: :member
    end
  end

  resources :bugs, only: [] do
    get 'user_bugs', on: :collection
  end

  resources :project_assignments, only: %i[new create destroy]

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  include PgSearch::Model

  has_many :project_assignments, dependent: :delete_all
  has_many :users, through: :project_assignments
  has_many :bugs, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :description, presence: true

  pg_search_scope :search_by_name, against: :name, using: { tsearch: { prefix: true } }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authorize_project, only: %i[show edit update destroy]
  before_action :authorize_new_project, only: %i[new create]

  def index
    @projects = policy_scope(Project)
    @projects = @projects.search_by_name(params[:search]) if params[:search].present?

    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @project_assignments = @project.project_assignments.includes(:user).drop(1)
  end

  def new
    @project = current_user.projects.new
  end

  def edit; end

  def create
    @project = current_user.projects.new(project_params)
    @project.project_assignments.build(user: current_user)

    if @project.save
      redirect_to project_path(@project), notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = 'Project was successfully destroyed.'
    else
      flash[:alert] = @project.errors.full_messages.to_sentence
    end
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def authorize_project
    authorize @project
  end

  def authorize_new_project
    authorize Project
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  def roles(user)
    user.roles.pluck(:name).join(', ')
  end

  def creator(project)
    project.project_assignments.first&.user
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, class: "col-12 col-md-6 col-lg-4 border border-radius-5 mt-5 p-4") do |form| %>
  <h3 class="form-heading mb-4"><%= form_type %></h3>

  <div class="form-group mb-4 field">
    <%= form.text_field :name, class: 'form-control', placeholder: "Name" %>
    <%= render "devise/shared/error_messages", resource: project, field: :name %>
  </div>

  <div class="form-group mb-4 field">
    <%= form.text_area :description, class: 'form-control', placeholder: "Description" %>
    <%= render "devise/shared/error_messages", resource: project, field: :description %>
  </div>

  <div class="form-group mb-4 actions">
    <%= form.submit class: 'btn btn-primary btn-submit' %>
  </div>
<% end %>

app/views/projects/_nav_links.html.erb
<% if policy(project).update? %>
  <%= link_to 'Edit', edit_project_path(project), class: "nav-btn btn btn-primary col-3 col-md-2 offset-1 offset-md-2" %>
  <%= link_to 'Add Developer', new_project_assignment_path(user_type: 'Developer', project_id: project.id), class: "nav-btn btn btn-primary col-4 col-md-2 offset-md-1" %>
  <%= link_to 'Add QA', new_project_assignment_path(user_type: 'QA', project_id: project.id), class: "nav-btn btn btn-primary col-3 col-md-2 offset offset-md-1" %>
<% end %>
<% if policy(Bug).create? %>
  <%= link_to 'Report Bug', new_project_bug_path(project), class: "nav-btn btn btn-primary col-4 col-md-2 offset-4 offset-md-5" %>
<% end %>

app/views/projects/_project.html.erb
<%= link_to '< Back', projects_path, class: "nav-btn btn btn-primary col-3 col-md-2 col-xxl-1 offset-1 offset-lg-2" %>
<%= link_to 'View Bugs >', project_bugs_path(project), class: "nav-btn btn btn-primary col-3 col-md-2 col-xxl-1 offset-4 offset-md-6 offset-lg-4 offset-xxl-6" %>
<div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 border border-radius-5 p-3">
  <h3 class="table-heading mb-2"><%= project.name %></h3>
  <h6 class="table-heading text-muted mb-4"><%= project.description %></h6>
  <p class="table-heading mb-4">
    <strong>Project Owner: </strong>
    <%= creator(project)&.name %>
  </p>

  <% if project_assignments.any? %>
    <div class="col-lg-10 offset-lg-1">
      <h3 class="table-heading">Assigned Users</h3>
      <table class="table table-hover table-responsive">
        <thead class="thead-light">
          <tr>
            <th class="col-3">Name</th>
            <th class="col-3">Roles</th>
            <th class="col-3">Remove</th>
          </tr>
        </thead>

        <tbody>
          <% project_assignments.each do |project_assignment| %>
            <tr>
              <td><%= "#{project_assignment.user.name}" %></td>
              <td><%= "#{roles(project_assignment.user)}" %></td>
              <% if policy(project_assignment).destroy? %>
                <td><%= link_to 'Remove User', project_assignment_path(id: project_assignment.id, project_id: project.id, user_id: project_assignment.user_id), method: :delete, class: "text-danger text-disabled" %></td>
              <% else %>
                <td class="text-muted">Remove User</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/projects/_projects_table.html.erb
<% if projects.empty? %>
  <h3 class="table-heading">No Projects Found!</h3>
<% else %>
  <table class="table table-hover table-responsive">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td><%= project.description %></td>
          <% if policy(project).edit? %>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <% else %>
            <td class="text-muted">Edit</td>
          <% end %>
          <% if policy(project).destroy? %>
            <td><%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td class="text-muted">Delete</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/projects/edit.html.erb
<div class="row justify-content-center">
  <%= render 'form', project: @project, form_type: "Edit Project" %>
</div>

app/views/projects/index.html.erb
<div class="col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3 border border-radius-5 p-3 mt-5">
  <h3 class="table-heading">Projects</h3>

  <%= render 'layouts/search_bar', path: projects_path, search_name: 'Projects' %>

  <div id="posts-table">
    <%= render 'projects_table', projects: @projects %>
  </div>
</div>

<% if policy(Project).create? %>
  <%= link_to 'New Project >', new_project_path, class: "nav-btn btn btn-primary col-4 col-md-3 col-lg-2 offset-7 offset-md-7" %>
<% end %>

app/views/projects/index.js.erb
$("#posts-table").html("<%= escape_javascript(render partial: 'projects_table', locals: { projects: @projects }) %>");

app/views/projects/new.html.erb
<div class="row justify-content-center">
  <%= render 'form', project: @project, form_type: "New Project" %>
</div>

<%= link_to '< Back', projects_path, class: "nav-btn btn btn-primary col-3 col-md-2 col-lg-1 offset-md-3 offset-lg-4" %>

app/views/projects/show.html.erb
<%= render 'project', project: @project, project_assignments: @project_assignments %>

<%= render 'nav_links', project: @project %>