config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :bugs do
      get 'assign', on: :member
    end
  end

  resources :bugs, only: [] do
    get 'user_bugs', on: :collection
  end

  resources :project_assignments, only: %i[new create destroy]

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  include PgSearch::Model

  belongs_to :project
  belongs_to :user
  belongs_to :dev, class_name: 'User', optional: true
  has_one_attached :image, dependent: :destroy

  enum bug_type: { feature: 0, bug: 1 }
  enum status: { new: 0, started: 1, completed: 2, resolved: 3 }, _prefix: true

  validates :title, :status, :bug_type, :deadline, presence: true
  validates :title, uniqueness: { scope: :project_id }, length: { maximum: 255 }
  validate :image_type
  validate :deadline_cannot_be_in_the_past, if: :deadline_changed?

  pg_search_scope :search_by_title, against: :title, using: { tsearch: { prefix: true } }

  private

  def image_type
    return unless image.attached?

    errors.add(:image, 'needs to be a gif or png!') unless image.content_type.in?(%('image/gif image/png'))
  end

  def deadline_cannot_be_in_the_past
    errors.add(:deadline, 'cannot be in the past!') if deadline < Time.current
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  before_action :set_bug, only: %i[show edit update assign destroy]
  before_action :set_project, except: :user_bugs
  before_action :authorize_bug, only: %i[show edit update assign destroy]
  before_action :authorize_new_bug, only: %i[new create]
  before_action :authorize_project, only: :index
  before_action :set_bug_type, only: %i[edit update destroy]

  def index
    @bugs = @project.bugs
    @bugs = @bugs.search_by_title(params[:search]) if params[:search].present?

    respond_to do |format|
      format.js
      format.html
    end
  end

  def show; end

  def new
    @bug = @project.bugs.new
  end

  def edit; end

  def create
    @bug = @project.bugs.new(bug_params)
    if @bug.save
      redirect_to project_bug_path(@project, @bug), notice: "#{@bug.bug_type.capitalize} was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bug.update(bug_params)
      redirect_to project_bug_path(@project, @bug), notice: "#{@bug_type} was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def assign
    if @bug.update(dev_id: current_user.id)
      flash[:notice] = "#{@bug.bug_type.capitalize} was successfully assigned to you."
    else
      flash[:alert] = @bug.errors.full_messages.to_sentence
    end
    redirect_to project_bug_path(@project, @bug)
  end

  def user_bugs
    @bugs = policy_scope(Bug)
  end

  def destroy
    if @bug.destroy
      flash[:notice] = "#{@bug_type} was successfully destroyed."
    else
      flash[:alert] = @bug.errors.full_messages.to_sentence
    end
    redirect_to project_bugs_path(@project)
  end

  private

  def set_bug
    @bug = Bug.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def bug_params
    params.require(:bug).permit(:title, :description, :deadline, :bug_type, :status,
                                :image).merge(user_id: current_user.id)
  end

  def authorize_bug
    authorize @bug
  end

  def authorize_new_bug
    authorize Bug
  end

  def authorize_project
    authorize @project, :show?
  end

  def set_bug_type
    @bug_type = @bug.bug_type.capitalize
  end
end

app/views/bugs/_bugs_table.html.erb
<% if bugs.empty? %>
  <h3 class="table-heading">No Bugs Found!</h3>
<% else %>
  <table class="table table-hover table-responsive">
    <thead class="thead-light">
      <tr>
        <th>Title</th>
        <th>Deadline</th>
        <th>Type</th>
        <th>Status</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% bugs.each do |bug| %>
        <tr>
          <td><%= link_to bug.title, project_bug_path(project, bug) %></td>
          <td><%= bug.deadline %></td>
          <td><%= bug.bug_type.capitalize %></td>
          <td><%= bug.status.capitalize %></td>
          <% if policy(bug).edit? %>
            <td><%= link_to 'Edit', edit_project_bug_path(project, bug) %></td>
          <% else %>
            <td class="text-muted">Edit</td>
          <% end %>
          <% if policy(bug).destroy? %>
            <td><%= link_to 'Delete', project_bug_path(project, bug), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td class="text-muted">Delete</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/bugs/_form.html.erb
<%= form_with(model: [project, bug], local: true, class: "col-12 col-md-6 col-lg-4 border border-radius-5 mt-5 p-4") do |form| %>
  <h3 class="form-heading mb-4">Edit <%= @bug_type %></h3>

  <% if policy(Bug).create? %>
    <div class="form-group mb-4 field">
      <%= form.label :title, class: 'mb-2' %>
      <%= form.text_field :title, class: 'form-control', autofocus: true, autocomplete: "title" %>
      <%= render "devise/shared/error_messages", resource: bug, field: :title %>
    </div>

    <div class="form-group mb-4 field">
      <%= form.label :description, class: 'mb-2' %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group mb-4 field">
      <%= form.label :deadline, class: 'mb-2' %><br>
      <%= form.datetime_select :deadline, {}, { class: 'datepicker text-muted' } %>
      <%= render "devise/shared/error_messages", resource: bug, field: :deadline %>
    </div>

    <% if @bug.image.attached? %>
      <p>
        <%= cl_image_tag(@bug.image.key, width: 500, id: 'previous-img') %>
      </p>
    <% end %>

    <div id="target"></div>

    <div class="form-group mb-4 field">
      <%= form.label :image, class: 'mb-2' %>
      <%= form.file_field(:image, accept: 'image/png,image/gif', direct_upload: true, class: 'form-control') %>
      <%= render "devise/shared/error_messages", resource: bug, field: :image %>
    </div>

    <div class="form-group mb-4 field">
      <%= form.label :bug_type, class: 'mb-2' %>
      <%= form.select :bug_type, options_for_select(Bug.bug_types.map {|k, v| [k.humanize.capitalize, k, {:id => k}]}, @bug.bug_type), {}, { autocomplete: "bug_type", class: 'form-select' } %>
    </div>
  <% end %>

  <div class="form-group mb-4 field">
    <%= form.label :status, class: 'mb-2' %>
    <%= form.select :status, options_for_select(Bug.statuses.map {|k, v| [k.humanize.capitalize, k, {:id => k}]}, @bug.status), {}, { autocomplete: "status", class: 'form-select' } %>
  </div>

  <div class="form-group mb-4 actions">
    <%= form.submit class: 'btn btn-primary btn-submit' %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1 id="bug_heading", name="<%= @bug_type %>">Edit <%= @bug_type %></h1>

<div class="row justify-content-center">
  <%= render 'form', bug: @bug, project: @project, bug_type: @bug_type %>
</div>

app/views/bugs/index.html.erb
<div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 border border-radius-5 p-3 mt-5">
  <h3 class="table-heading">Bugs</h3>

  <%= render 'layouts/search_bar', path: project_bugs_path(@project), search_name: 'Bugs' %>

  <div id="bugs-table">
    <%= render 'bugs_table', project: @project, bugs: @bugs %>
  </div>
</div>


<%= link_to '< Back', project_path(@project), class: "nav-btn btn btn-primary col-3 col-md-3 offset-1 col-lg-2 offset-md-1 offset-lg-2" %>

<% if policy(Bug).create? %>
  <%= link_to 'New Bug >', new_project_bug_path(@project), class: "nav-btn btn btn-primary col-3 col-md-3 col-lg-2 offset-4 offset-md-4 offset-lg-4" %>
<% end %>

app/views/bugs/index.js.erb
$("#bugs-table").html("<%= escape_javascript(render partial: 'bugs_table', locals: { project: @project, bugs: @bugs }) %>");

app/views/bugs/new.html.erb
<h1 id="bug_heading", name="<%= @bug_type %>">Editing <%= @bug_type %></h1>

<div class="row justify-content-center">
  <%= render 'form', bug: @bug, project: @project, form_type: "New Bug" %>
</div>

<%= link_to '< Back', project_path(@project), class: "nav-btn btn btn-primary col-3 col-md-2 col-lg-1 offset-md-3 offset-lg-4" %>

app/views/bugs/show.html.erb
<div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 border border-radius-5 p-3 mt-5">
  <h3 class="table-heading mb-2"><%= @bug.title %></h3>
  <h6 class="table-heading text-muted mb-4"><%= @bug.description %></h6>

  <div class="row justify-content-around">
    <p class="col-12 col-md-9 col-lg-3 text-center">
      <strong>Deadline:</strong>
      <%= @bug.deadline %>
    </p>

    <p class="col-12 col-md-4 col-lg-3 text-center">
      <strong>Type:</strong>
      <%= @bug.bug_type.capitalize %>
    </p>

    <p class="col-12 col-md-4 col-lg-3 text-center">
      <strong>Status:</strong>
      <%= @bug.status.capitalize %>
    </p>

    <% if @bug.image.attached? %>
      <p class="col-12 col-md-8 col-lg-6 text-center mt-5">
        <%= cl_image_tag(@bug.image.key, width: 500, id: 'img-bug') %>
      </p>
    <% end %>
  </div>
</div>

<% if policy(@bug).edit? %>
  <%= link_to '< Edit', edit_project_bug_path(@project, @bug), class: "nav-btn btn btn-primary col-3 col-md-3 col-lg-2 offset-1 offset-lg-2" %>
<% else %>
  <%= link_to '', '#', class: "btn col-3 col-md-3 col-lg-2 offset-1 offset-lg-2" %>
<% end %>

<% if policy(@bug).assign? %>
  <%= link_to 'Assign Myself >', assign_project_bug_path(@project, @bug), class: "nav-btn btn btn-primary col-3 col-md-3 col-lg-2 offset-4 offset-md-4 offset-lg-4" %>
<% end %>

app/views/bugs/user_bugs.html.erb
<% if @bugs.empty? %>
  <div class=" counter col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3 border border-radius-5 p-3 mt-3">
    <h3 class="count-heading mt-3 mx-4">You don't have any bugs yet!</h3>
  </div>
<% else %>
  <div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 border border-radius-5 p-3 mt-5">
    <h3 class="table-heading">Your Bugs</h3>

    <table class="table table-hover table-responsive">
      <thead class="thead-light">
        <tr>
          <th>Title</th>
          <th>Deadline</th>
          <th>Type</th>
          <th>Status</th>
          <th>Project</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>

      <tbody>
        <% @bugs.includes(:project).each do |bug| %>
          <tr>
            <td><%= link_to bug.title, project_bug_path(bug.project, bug) %></td>
            <td><%= bug.deadline %></td>
            <td><%= bug.bug_type.capitalize %></td>
            <td><%= bug.status.capitalize %></td>
            <td><%= link_to bug.project.name, project_path(bug.project) %></td>
            <% if policy(bug).edit? %>
              <td><%= link_to 'Edit', edit_project_bug_path(bug.project, bug) %></td>
            <% else %>
              <td class="text-muted">Edit</td>
            <% end %>
            <% if policy(bug).destroy? %>
              <td><%= link_to 'Delete', project_bug_path(bug.project, bug), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td class="text-muted">Delete</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>