config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :bugs do
      get 'assign', on: :member
    end
  end

  resources :bugs, only: [] do
    get 'user_bugs', on: :collection
  end

  resources :project_assignments, only: %i[new create destroy]

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/views/layouts/_alerts.html.erb
<p class="notice m-0 mt-2 p-0 text-primary text-center"><%= notice %></p>
<p class="alert m-0 mt-2 p-0 text-danger text-center"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg px-5">
  <%= link_to 'Bugzilla', projects_path, class: "navbar-brand" %>
  <%# <a class="navbar-brand" href="#">Bugzilla</a> %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active px-4">
        <%= link_to 'My Bugs', user_bugs_bugs_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item px-4">
        <%= link_to 'Settings', edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item px-4">
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_search_bar.html.erb
<%= form_tag(path, method: :get, remote: true, "data-type": :"script",  class: "form-group col-5 col-md-4 col-xl-3 offset-7 offset-md-8 offset-xl-9 mb-3") do %>
  <% if search_name == 'Users' %>
    <%= hidden_field_tag :user_type, @user_type %>
    <%= hidden_field_tag :project_id, @project_id %>
  <% end %>
  <div class="input-group">
    <%= text_field_tag(:search, params[:search], class: "form-control search-field d-inline w-75", placeholder: "Search #{search_name}") %>
    <%= button_tag(type: "submit", class: "btn btn-submit btn-primary d-inline w-25") do %>
      <i class="fa fa-search"></i>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>